port: 7890
socks-port: 7891
allow-lan: true
mode: rule
ipv6: true
log-level: info
unified-delay: true
global-client-fingerprint: chrome
external-controller: '0.0.0.0:9090'
external-ui: /usr/local/etc/clash/ui
secret: 123456
dns:
  enable: true
  listen: :1053
  ipv6: true
  fake-ip-range: 28.0.0.1/8
  enhanced-mode: fake-ip 
  use-hosts: true 
  nameserver:
    - 127.0.0.1:2053 
  fallback:
    - 1.1.1.1 
    - 8.8.8.8
  fallback-filter:
    geoip: true 
    ipcidr:
      - 240.0.0.0/4
  default-nameserver:
    - 127.0.0.1:2053
proxies:
- name: RN-vless               
  type: vless
  server: 88.88.88.88.88                           
  port: 2443                                
  uuid: 34c18fad-ec2f-4e75-aea6-d78e6d45a550   
  network: tcp
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: www.yahoo.com                 
  reality-opts: 
    public-key: f1qn-AHx1S35vIjCgVqjad9Yc45RDXfn7bCTRF5koSU    
    short-id: '96770c21'                    
  client-fingerprint: chrome                  
- name: RN-ws                        
  type: vmess
  server: 88.88.88.88.88                        
  port: 3443                                     
  uuid: 34c18fad-ec2f-4e75-aea6-d78e6d45a550       
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  servername: www.bing.com                    
  ws-opts:
    path: "34c18fad-ec2f-4e75-aea6-d78e6d45a550-vm"                             
    headers:
      Host: www.bing.com                     
- name: RN-hy2                          
  type: hysteria2                                      
  server: 88.88.88.88.88                               
  port: 9443                                
  password: 34c18fad-ec2f-4e75-aea6-d78e6d45a550                          
  alpn:
    - h3
  sni: www.bing.com                               
  skip-cert-verify: true
  fast-open: true
- name: RN-tuic5                          
  server: 88.88.88.88.88                      
  port: 8443                                    
  type: tuic
  uuid: 34c18fad-ec2f-4e75-aea6-d78e6d45a550       
  password: 34c18fad-ec2f-4e75-aea6-d78e6d45a550   
  alpn: [h3]
  disable-sni: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
  sni: www.bing.com                                
  skip-cert-verify: true
- name: BW-vless               
  type: vless
  server: 88.88.88.88.88                           
  port: 2443                                
  uuid: 03f32af4-750c-4869-b3a2-ce35592fa744   
  network: tcp
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: www.yahoo.com                 
  reality-opts: 
    public-key: tTIbe-TH9pGCmUCI8jklnY8LNscaTIk-xYWVbDSD_yQ    
    short-id: '73ef4cb6'                    
  client-fingerprint: chrome                  
- name: BW-ws                        
  type: vmess
  server: 88.88.88.88.88                        
  port: 3443                                     
  uuid: 03f32af4-750c-4869-b3a2-ce35592fa744       
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  servername: www.bing.com                    
  ws-opts:
    path: "03f32af4-750c-4869-b3a2-ce35592fa744-vm"                             
    headers:
      Host: www.bing.com                     
- name: BW-hy2                           
  type: hysteria2                                      
  server: 88.88.88.88.88                               
  port: 9443                                
  password: 03f32af4-750c-4869-b3a2-ce35592fa744                          
  alpn:
    - h3
  sni: www.bing.com                               
  skip-cert-verify: true
  fast-open: true
- name: BW-tuic5                            
  server: 88.88.88.88.88                      
  port: 8443                                    
  type: tuic
  uuid: 03f32af4-750c-4869-b3a2-ce35592fa744       
  password: 03f32af4-750c-4869-b3a2-ce35592fa744   
  alpn: [h3]
  disable-sni: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
  sni: www.bing.com                                
  skip-cert-verify: true  
- name: CD-vless               
  type: vless
  server: 88.88.88.88.88                           
  port: 2443                                
  uuid: a2c842d2-e629-4d48-b1ea-d16ccbdc75d9   
  network: tcp
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: www.yahoo.com                 
  reality-opts: 
    public-key: hNOGsu1ZgaqWqZsiF65ZDukKdYdLd87i2E8a5mTSeiw    
    short-id: 'd36a9946'                      
  client-fingerprint: chrome                  
- name: CD-ws                         
  type: vmess
  server: 88.88.88.88.88                        
  port: 3443                                     
  uuid: a2c842d2-e629-4d48-b1ea-d16ccbdc75d9       
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  servername: www.bing.com                    
  ws-opts:
    path: "a2c842d2-e629-4d48-b1ea-d16ccbdc75d9-vm"                             
    headers:
      Host: www.bing.com                     
- name: CD-hy2                            
  type: hysteria2                                      
  server: 88.88.88.88.88                               
  port: 9443                                
  password: a2c842d2-e629-4d48-b1ea-d16ccbdc75d9                          
  alpn:
    - h3
  sni: www.bing.com                               
  skip-cert-verify: true
  fast-open: true
- name: CD-tuic5                            
  server: 88.88.88.88.88                      
  port: 8443                                    
  type: tuic
  uuid: a2c842d2-e629-4d48-b1ea-d16ccbdc75d9       
  password: a2c842d2-e629-4d48-b1ea-d16ccbdc75d9   
  alpn: [h3]
  disable-sni: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
  sni: www.bing.com                                
  skip-cert-verify: true
proxy-groups:
- name: Ë¥üËΩΩÂùáË°°
  type: load-balance
  url: https://www.gstatic.com/generate_204
  interval: 300
  strategy: round-robin
  proxies:
    - RN-vless                             
    - RN-ws
    - RN-hy2
    - RN-tuic5
    - CD-vless                             
    - CD-ws
    - CD-hy2
    - CD-tuic5
    - BW-vless                             
    - BW-ws
    - BW-hy2
    - BW-tuic5
- name: Ëá™Âä®ÈÄâÊã©
  type: url-test
  url: https://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
    - RN-vless                             
    - RN-ws
    - RN-hy2
    - RN-tuic5
    - CD-vless                             
    - CD-ws
    - CD-hy2
    - CD-tuic5
    - BW-vless                             
    - BW-ws
    - BW-hy2
    - BW-tuic5	    
- name: üåçÈÄâÊã©‰ª£ÁêÜËäÇÁÇπ
  type: select
  proxies:
    - Ë¥üËΩΩÂùáË°°                                         
    - Ëá™Âä®ÈÄâÊã©
    - DIRECT
    - RN-vless                             
    - RN-ws
    - RN-hy2
    - RN-tuic5
    - CD-vless                             
    - CD-ws
    - CD-hy2
    - CD-tuic5
    - BW-vless                             
    - BW-ws
    - BW-hy2
    - BW-tuic5 
rules:
  - DOMAIN,v2rayssr.com,üåçÈÄâÊã©‰ª£ÁêÜËäÇÁÇπ
  - DOMAIN,bulianglin.com,üåçÈÄâÊã©‰ª£ÁêÜËäÇÁÇπ 
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,üåçÈÄâÊã©‰ª£ÁêÜËäÇÁÇπ

